title: Install Software
description: Installs selected browsers, media players, archivers, and game launchers with predefined settings and policies
actions:
  # DirectX
  - !writeStatus: {status: 'Installing DirectX'}
  - !software:
    name: 'directx'
    source: chocolatey
    package: 'directx'

  # Browsers
  - !writeStatus: {status: 'Installing Brave', option: browser-brave}
  - !download: 
    option: browser-brave
    url: 'https://github.com/brave/brave-browser/releases/latest/download/BraveBrowserStandaloneSetup.exe'
    destination: 'BraveBrowserStandaloneSetup.exe'
    package: 'brave'
  - !cmd: {command: 'start "BraveBrowserStandaloneSetup" /b /wait "BraveBrowserStandaloneSetup.exe" /silent /install', exeDir: true, option: browser-brave}
  - !powerShell: {command: '.\BROWSER.ps1 -Brave -uBlock', exeDir: true, option: browser-brave}

  - !writeStatus: {status: 'Installing Firefox', option: browser-firefox}
  - !software:
    option: browser-firefox
    name: 'firefox'
    source: chocolatey
  - !powerShell: {command: '.\BROWSER.ps1 -Firefox', exeDir: true, option: browser-firefox}

  - !writeStatus: {status: 'Installing Chrome', option: browser-chrome}
  - !software:
    option: browser-chrome
    name: 'googlechrome'
    source: chocolatey
  - !powerShell: {command: '.\BROWSER.ps1 -Chrome', exeDir: true, option: '!uninstall-edge'}

  - !writeStatus: {status: 'Installing LibreWolf', option: browser-librewolf}
  - !software:
    name: 'librewolf'
    source: chocolatey
    option: browser-librewolf
    package: 'librewolf'

  - !writeStatus: {status: 'Installing Helium', option: browser-helium}
  - !download:
    option: browser-helium
    url: 'https://github.com/imputnet/helium-windows/releases/latest/download/helium_0.17.0.1_x64-installer.exe'
    destination: 'HeliumInstaller.exe'
    package: 'helium'
  - !cmd: {command: 'start "HeliumInstaller" /b /wait "HeliumInstaller.exe" /S /SYSTEM', exeDir: true, option: browser-helium}
  - !powerShell: {command: '.\BROWSER.ps1 -Helium', exeDir: true, option: browser-helium}

  - !writeStatus: {status: 'Installing Zen Browser', option: browser-zen}
  - !download:
    option: browser-zen
    url: 'https://github.com/zen-browser/desktop/releases/latest/download/zen.installer.exe'
    destination: 'zen.installer.exe'
    package: 'zen'
  - !cmd: {command: 'start "ZenInstaller" /b /wait "zen.installer.exe" /S', exeDir: true, option: browser-zen}
  - !powerShell: {command: '.\BROWSER.ps1 -Zen', exeDir: true, option: browser-zen}

  - !status: {status: 'Configuring Edge', option: '!uninstall-edge'}
  - !powerShell: {command: '.\BROWSER.ps1 -Edge -uBlock', exeDir: true, option: '!uninstall-edge'}

  # Media players
  - !writeStatus: {status: 'Installing MPC-HC', option: mpc-hc}
  - !software:
    option: mpc-hc
    name: 'mpc-hc'
    source: chocolatey

  - !writeStatus: {status: 'Installing VLC', option: vlc}
  - !software:
    option: vlc
    name: 'vlc'
    source: chocolatey

  # Archivers
  - !writeStatus: {status: 'Installing 7zip', option: 7-zip}
  - !software:
    option: 7-zip
    name: '7zip'
    source: chocolatey

  - !writeStatus: {status: 'Installing WinRAR', option: winrar}
  - !software:
    option: winrar
    name: 'winrar'
    source: chocolatey

  # Launchers 
  - !writeStatus: {status: 'Installing Steam', option: steam}
  - !software:
    option: steam
    name: 'steam'
    source: chocolatey

  - !writeStatus: {status: 'Installing EA app', option: ea-app}
  - !software:
    option: ea-app
    name: 'ea-app'
    source: chocolatey
  - !taskKill: {name: 'EA*'}

  - !writeStatus: {status: 'Installing Epic Games', option: epicgameslauncher}
  - !software:
    option: epicgameslauncher
    name: 'epicgameslauncher'
    source: chocolatey

  - !writeStatus: {status: 'Installing Ubisoft', option: ubisoft-connect}
  - !software:
    option: ubisoft-connect
    name: 'ubisoft-connect'
    source: chocolatey

  # Development Tools
  - !writeStatus: {status: 'Installing Visual Studio Code', option: vscode}
  - !software:
    option: vscode
    name: 'vscode'
    source: chocolatey

  - !writeStatus: {status: 'Installing Visual Studio 2026', option: vs2026}
  - !software:
    option: vs2026
    name: 'visualstudio2026community'
    source: chocolatey

  - !writeStatus: {status: 'Installing Git', option: git}
  - !software:
    option: git
    name: 'git'
    source: chocolatey

  - !writeStatus: {status: 'Installing Notepad++', option: notepadplusplus}
  - !software:
    option: notepadplusplus
    name: 'notepadplusplus'
    source: chocolatey