title: Network Settings
description: Optimized network stack.
actions:
  # Disabling legacy broadcast protocols
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient', value: 'EnableMulticast', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters', value: 'EnableMulticast', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\NetBT\Parameters', value: 'EnableLMHOSTS', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Wpad', value: 'WpadOverride', type: REG_DWORD, data: '1'}

  - !powerShell:
      command: |
        Get-ChildItem 'HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces' | ForEach-Object {
            Set-ItemProperty -Path $_.PSPath -Name 'NetbiosOptions' -Type DWord -Value 2 -Force
        }
      runas: currentUserElevated
      wait: true

  # Parallel network processing
  - !run: {exe: 'netsh', args: 'int tcp set global rss=enabled'}

  # Disabling packet coalescing 
  - !run: {exe: 'netsh', args: 'int tcp set global rsc=disabled'}

  # Speed up initial connection setup
  - !run: {exe: 'netsh', args: 'int tcp set global fastopen=enabled'}
  - !run: {exe: 'netsh', args: 'int tcp set global fastopenfallback=enabled'}

  # Disabling TCP heuristics 
  - !run: {exe: 'netsh', args: 'int tcp set heuristics forcews=disabled'}

  # Disabling UDP batching
  - !run: {exe: 'netsh', args: 'int udp set global uro=disabled'}

  # Offloading UDP segmentation to NIC
  - !run: {exe: 'netsh', args: 'int udp set global uso=enabled'}

  # Checksum offload
  - !run: {exe: 'netsh', args: 'int ipv4 set global taskoffload=enabled'}